import keyMirror from 'key-mirror'

export default keyMirror({
	LOAD_DATA_SUCCESS: null,
	AUTH_SUCCESS: null,
	ERROR_MSG: null,
	LOGOUT_SUCCESS: null,
	ADD_OWNER_SUCCESS: null,
	
	GET_OWNERINFO_SUCCESS: null,
	DEL_OWNER_SUCCESS: null,
	GET_OWNERNAME_SUCCESS: null,
	GET_OWNERNUM_SUCCESS: null,
	GET_ADMINNUM_SUCCESS: null,
	GET_ADMINNUMLIST_SUCCESS: null,

	GET_PERSONINFO_SUCCESS: null,
	UPDATE_PERSONINFO_SUCCESS: null,
	GET_FAMILYMEMBER_SUCCESS: null,
	ADD_FAMILYMEMBER_SUCCESS: null,
	DEL_FAMILYMEMBER_SUCCESS: null,
	UPDATE_FAMILYMEMBER_SUCCESS: null,
	GET_FAMILYMEMBERNUM_SUCCESS: null,

	GET_HOUSEINFO_SUCCESS: null,

	GET_COMMUNITYLIST_SUCCESS: null,
	ADD_COMMUNITY_SUCCESS: null,
	DEL_COMMUNITY_SUCCESS: null,
	UPDATE_COMMUNITY_SUCCESS: null,
	GET_COMMUNITYNAME_SUCCESS: null,

	GET_BUILDINGLIST_SUCCESS: null,
	ADD_BUILDING_SUCCESS: null,
	DEL_BUILDING_SUCCESS: null,
	UPDATE_BUILDING_SUCCESS: null,
	GET_BUILDINGNAME_SUCCESS: null,

	GET_UNITLIST_SUCCESS: null,
	ADD_UNIT_SUCCESS: null,
	DEL_UNIT_SUCCESS: null,
	UPDATE_UNIT_SUCCESS: null,
	GET_UNITNAME_SUCCESS: null,

	GET_ROOMLIST_SUCCESS: null,
	ADD_ROOM_SUCCESS: null,
	DEL_ROOM_SUCCESS: null,
	UPDATE_ROOM_SUCCESS: null,
	GET_ONEROOM_SUCCESS: null,
	GET_ROOMBYUSESR_SUCCESS: null,
	GET_ROOMNAME_SUCCESS: null,
	GET_ROOMNUM_SUCCESS: null,

	GET_COSTLIST_SUCCESS: null,
	ADD_COST_SUCCESS: null,
	DEL_COST_SUCCESS: null,
	UPDATE_COST_SUCCESS: null,
	GET_COSTNAME_SUCCESS: null,

	GET_CHARGELIST_SUCCESS: null,
	ADD_CHARGE_SUCCESS: null,
	DEL_CHARGE_SUCCESS: null,
	UPDATE_CHARGE_SUCCESS: null,
	GET_CHARGEBYUSER_SUCCESS: null,

	GET_GARAGELIST_SUCCESS: null,
	ADD_GARAGE_SUCCESS: null,
	DEL_GARAGE_SUCCESS: null,
	UPDATE_GARAGE_SUCCESS: null,
	GET_GARAGEBYUSER_SUCCESS: null,
	GET_GARAGENUM_SUCCESS: null,

	GET_REPAIRLIST_SUCCESS: null,
	ADD_REPAIR_SUCCESS: null,
	DEL_REPAIR_SUCCESS: null,
	UPDATE_REPAIR_SUCCESS: null,
	GET_REPAIRBYUSER_SUCCESS: null,

	GET_COMPLAINTLIST_SUCCESS: null,
	ADD_COMPLAINT_SUCCESS: null,
	DEL_COMPLAINT_SUCCESS: null,
	UPDATE_COMPLAINT_SUCCESS: null,
	GET_COMPLAINTBYUSER_SUCCESS: null,

	GET_PAYURL_SUCCESS: null,

	GET_ANNOUNCEMENTLIST_SUCCESS: null,
	ADD_ANNOUNCEMENT_SUCCESS: null,
	DEL_ANNOUNCEMENT_SUCCESS: null,
	UPDATE_ANNOUNCEMENT_SUCCESS: null,
	GET_ANNOUNCEMENTBYUSER_SUCCESS: null,
	GET_ONEANNOUNCEMENT_SUCCESS: null,
	GET_ANNOUNCEMENTLISTBYSTATUS_SUCCESS: null,

	GET_ANNOUNCEMENTREADLIST_SUCCESS: null,
	GET_READANNOUNCEMENT_SUCCESS: null,
	GET_RECVANNOUNCEMENT_SUCCESS: null,
});
