import keyMirror from 'key-mirror'

export default keyMirror({
	LOAD_DATA_SUCCESS: null,
	AUTH_SUCCESS: null,
	ERROR_MSG: null,
	LOGOUT_SUCCESS: null,
	
	GET_OWNERINFO_SUCCESS: null,

	GET_PERSONINFO_SUCCESS: null,
	UPDATE_PERSONINFO_SUCCESS: null,
	GET_FAMILYMEMBER_SUCCESS: null,
	ADD_FAMILYMEMBER_SUCCESS: null,
	DEL_FAMILYMEMBER_SUCCESS: null,
	UPDATE_FAMILYMEMBER_SUCCESS: null,

	GET_HOUSEINFO_SUCCESS: null,

	GET_COMMUNITYLIST_SUCCESS: null,
	ADD_COMMUNITY_SUCCESS: null,
	DEL_COMMUNITY_SUCCESS: null,
	UPDATE_COMMUNITY_SUCCESS: null,

	GET_BUILDINGLIST_SUCCESS: null,
	ADD_BUILDING_SUCCESS: null,
	DEL_BUILDING_SUCCESS: null,
	UPDATE_BUILDING_SUCCESS: null,

	GET_UNITLIST_SUCCESS: null,
	ADD_UNIT_SUCCESS: null,
	DEL_UNIT_SUCCESS: null,
	UPDATE_UNIT_SUCCESS: null,

	GET_ROOMLIST_SUCCESS: null,
	ADD_ROOM_SUCCESS: null,
	DEL_ROOM_SUCCESS: null,
	UPDATE_ROOM_SUCCESS: null,
});
